### ISSUE TITLE
Issue: Air vs ground grid cost values in non ground pathable areas

### ISSUE THREAD

**Issue by raspersc2** [eladyaniv01/SC2MapAnalysis#81]
`self.get_air_vs_ground_grid()` creates a grid where by default, the ground pathable tiles have a cost of `100` and non pathable of `1`. Pretend we add cost to the grid because we see a marine: 
```python
air_vs_ground_grid = self.get_air_vs_ground_grid()
pos = marine.position
air_vs_ground_grid = self.add_cost(
            position=(int(pos.x), int(pos.y)),
            radius=marine.range,
            grid=air_vs_ground_grid,
            weight=10,
        )
```

Then the cost values over ground pathable tiles will correctly update to `110` and non pathable will now be `11`

Everything works as it should, but the problem with this, is that units will favour the non pathable tile with a value of 11 (which is now dangerous) over a perfectly safe ground tile that has a default value of 100

My suggestion is that when cost is added over a non pathable area because the radius spans over a non pathable area, the default value for the ground pathable tiles is also added.

Highlighted in red on the picture is an example of what the air vs ground grid thinks is safe, but really it's a dangerous area (in this picture the default weight for pathable areas was set to `50`).

![grid](https://user-images.githubusercontent.com/63355562/93188886-7072f500-f739-11ea-9ed9-e1e9210a128b.png)

**Comment by eladyaniv01** [comment]
That is a very interesting issue,  and very relevant to this grid, since the grid should be used vs ground units that shoot up

`My suggestion is that when cost is added over a non pathable area because the radius spans over a non pathable area, the default value for the ground pathable tiles is also added.`

Sounds like this is a solution,  i will play around with that idea
